### ISSUE TITLE
how to host this on apache2?

### ISSUE THREAD

**Issue by jacksolutions** [seedss/yii2-angular-seed#1]
can you please write possible configuration for this seed to run on apache2?

**Comment by CraryPrimitiveMan** [comment]
Is it OK? @jacksolutions

**Comment by jacksolutions** [comment]
yes that is good but another problem is,

in my local PC i have many project folders which i access them using http://localhost/project1 http://localhost/project2 etc and my document root is /var/www/

but according to you "config with apache2" section that you written in readme.md file it will stop working my other project cause i am changing document root to yii-angular-seed folder.. 

can i achieve the same without changing the document root and just applying htacess rules in htaccess and it works like this

http:/localhost/yii-angular-seed ??

many thanks,

**Comment by CraryPrimitiveMan** [comment]
@jacksolutions Use the server name, add `yii2-angular-seed.com` into your hosts. Your can access the site like the followings:
`http://yii2-angular-seed.com`

**Comment by jacksolutions** [comment]
that part i understand very well, thank you very much, so there is no way without adding that server name into my hosts?

**Comment by CraryPrimitiveMan** [comment]
@jacksolutions Maybe there is a way to do this, but I never try it. If you want to do this,  you need to change the `.htaccess` files.
